import random

MIN_ASCII = 33
MAX_ASCII = 126
RANGE_SIZE = MAX_ASCII - MIN_ASCII + 1

def encrypt_password(password: str) -> str:
    encryption = []

    for char in password:
        shifted_val = (ord(char) - MIN_ASCII + 13) % RANGE_SIZE
        encryption.append(chr(shifted_val + MIN_ASCII))
        
        encryption.append(chr(random.randint(MIN_ASCII, MAX_ASCII)))

    return "".join(encryption)


def decrypt_password(enc_password: str) -> str:
    decryption = []

    for i in range(len(enc_password)):
        if i % 2 == 0:
            shifted_val = (ord(enc_password[i]) - MIN_ASCII - 13) % RANGE_SIZE
            decryption.append(chr(shifted_val + MIN_ASCII))

    return "".join(decryption)

if __name__ == "__main__":
    choice = input("\nPress 1 to encrypt a password.\nPress 2 to decrypt an encyrpted password (that was generated by this script).\n")

    match choice:
        case "1":
            pwrd = input("\nType a password: ").strip()
            print("Here is your encypted password: " + encrypt_password(password=pwrd))

        case "2":
            encrypted_pwrd = input("Type an encrypted password: ").strip()
            print("Here is your decrypted password: " + decrypt_password(enc_password=encrypted_pwrd))